### ISSUE TITLE
NullPointerException - receiveEnergyFacing(PowerCellTileEntity.java:150)

### ISSUE THREAD

**Issue by Sir-Will** [McJtyMods/RFToolsPower#4]
rftoolspower-1.12-1.0.0
```
java.lang.NullPointerException: Exception in server tick loop
	at mcjty.rftoolspower.blocks.PowerCellTileEntity.receiveEnergyFacing(PowerCellTileEntity.java:150)
	at mcjty.rftoolspower.blocks.PowerCellTileEntity.receiveEnergy(PowerCellTileEntity.java:108)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy$Cache.receiveEnergy(DuctUnitEnergy.java:434)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.sendEnergy(DuctUnitEnergy.java:273)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.transmitEnergy(DuctUnitEnergy.java:238)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.sendEnergy(DuctUnitEnergy.java:213)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.tickPass(DuctUnitEnergy.java:206)
	at cofh.thermaldynamics.duct.energy.GridEnergy.tickGrid(GridEnergy.java:104)
	at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:62)
	at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_781_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcjty.rftoolspower.blocks.PowerCellTileEntity.receiveEnergyFacing(PowerCellTileEntity.java:150)
	at mcjty.rftoolspower.blocks.PowerCellTileEntity.receiveEnergy(PowerCellTileEntity.java:108)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy$Cache.receiveEnergy(DuctUnitEnergy.java:434)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.sendEnergy(DuctUnitEnergy.java:273)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.transmitEnergy(DuctUnitEnergy.java:238)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.sendEnergy(DuctUnitEnergy.java:213)
	at cofh.thermaldynamics.duct.energy.DuctUnitEnergy.tickPass(DuctUnitEnergy.java:206)
	at cofh.thermaldynamics.duct.energy.GridEnergy.tickGrid(GridEnergy.java:104)
	at cofh.thermaldynamics.util.WorldGridList.tickEnd(WorldGridList.java:62)
	at cofh.thermaldynamics.util.TickHandler.tick(TickHandler.java:93)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_781_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3985)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by McJty** [comment]
I'll fix this for next version
