### ISSUE TITLE
powercell crash 

### ISSUE THREAD

**Issue by christomite** [McJtyMods/RFToolsPower#46]
i placed the low tier powercell and it crashed my game now i cant even get back into  game ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/1/20 11:39 AM
Description: Tesselating block model

net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: rftoolspower:rftoolspower:block/cellhoriz_t1
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:38) ~[?:?] {re:classloading}
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:47) ~[?:?] {re:classloading}
	at mcjty.rftoolspower.modules.powercell.client.PowerCellBakedModel.getTopTexture(PowerCellBakedModel.java:66) ~[?:1.15-2.0.0-alpha] {re:classloading}
	at mcjty.rftoolspower.modules.powercell.client.PowerCellBakedModel.getQuads(PowerCellBakedModel.java:98) ~[?:1.15-2.0.0-alpha] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:81) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:887) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:422) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.18.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/1620041759.call(Unknown Source) [forge-1.15.2-31.1.18.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:38)
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:47)
	at mcjty.rftoolspower.modules.powercell.client.PowerCellBakedModel.getTopTexture(PowerCellBakedModel.java:66)
	at mcjty.rftoolspower.modules.powercell.client.PowerCellBakedModel.getQuads(PowerCellBakedModel.java:98)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:81)

-- Block model being tesselated --
Details:
	Block: Block{rftoolspower:cell1}[lower=false,upper=false]
	Block location: World: (-1251,69,3325), Chunk: (at 13,4,13 in -79,207; contains blocks -1264,0,3312 to -1249,255,3327), Region: (-3,6; contains chunks -96,192 to -65,223, blocks -1536,0,3072 to -1025,255,3583)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:51)

-- Block being tesselated --
Details:
	Block: Block{rftoolspower:cell1}[lower=false,upper=false]
	Block location: World: (-1251,69,3325), Chunk: (at 13,4,13 in -79,207; contains blocks -1264,0,3312 to -1249,255,3327), Region: (-3,6; contains chunks -96,192 to -65,223, blocks -1536,0,3072 to -1025,255,3583)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:62)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164)
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:784)
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:887)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:600)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['GOOBERBOMB1'/114, l='MpServer', x=-1250.72, y=69.00, z=3329.02]]
	Chunk stats: Client Chunk Cache: 961, 625
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -5203727232643234226
	Level generator: ID 07 - terraforged, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (176,115,48), Chunk: (at 0,7,0 in 11,3; contains blocks 176,0,48 to 191,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 852118 game time, 1197396 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$423/1620041759.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6221367032 bytes (5933 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
	Mod List: 
		Simple-Portals-Mod-1.15.2.jar Simple Portals {simpleportals@1.15.2-1.7.0.0 DONE}
		nethercraft-1.15.2-1.0.6.jar Nethercraft {nethercraft@1.0.6 DONE}
		chanceglobe-1.15.2-v1.3.1.jar Chance Globe {chanceglobe@v1.3.1 DONE}
		Macaws-Windows-Mod-1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		Silents-Mechanisms-Mod-1.15.2.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 DONE}
		Essentials-Mod-1.15.2.jar Essentials {essentials@1.15.2-2.7.0 DONE}
		ForgeEndertech-1.15.2.jar Forge Endertech {forgeendertech@6.0.0.0 DONE}
		TerraForged-Mod-1.15.2.jar TerraForged {terraforged@0.0.9 DONE}
		XaerosWorldMap_1.5.4_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.4 DONE}
		Just-Another-Rotten-Flesh-to-Leather-Mod-1.15.2.jar JRFTL {jrftl@1.1 DONE}
		Placebo-1.15.2.jar Placebo {placebo@3.0.2 DONE}
		Powah-Mod-1.15.2.jar Powah {powah@1.0.1 DONE}
		u_team_core-1.15.2-2.10.0.146.jar U Team Core {uteamcore@2.10.0.146 DONE}
		Apotheosis-Mod-1.15.2.jar Apotheosis {apotheosis@3.0.4 DONE}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		PattysMoreStuff-Mod-1.15.2.jar pattysmorestuff {pattysmorestuff@1.2.4 DONE}
		Refined-Storage-Mod-1.15.2.jar Refined Storage {refinedstorage@1.8.1 DONE}
		Industrial-Foregoing-Mod-1.15.2.jar Industrial Foregoing {industrialforegoing@2.2.1 DONE}
		useful_backpacks-1.15.2-1.9.0.52.jar Useful Backpacks {usefulbackpacks@1.9.0.52 DONE}
		Lollipop-Library-1.15.2.jar Lollipop {lollipop@1.0.1 DONE}
		ironfurnaces-1.15.2-2.0.1.jar Iron Furnaces {ironfurnaces@2.0.1 DONE}
		Structure-Compass-Mod-1.15.2.jar Structure Compass Mod {structurecompass@1.2 DONE}
		Advanced-Mining-Dimension-Mod-1.15.2.jar Mining World {mining_dimension@1.15.2-1.0.1 DONE}
		Silent-Gear-Mod-1.15.2.jar Silent Gear {silentgear@1.5.0+74 DONE}
		Horizontal-Glass-Panes-Mod-1.15.2.jar Horizontal Glass Panes {hgp@1.15.2 DONE}
		Simply-Light-Mod-1.15.2.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		tgcropesmod-1.15.2-1.2.0.jar Ropes Mod {tgcropesmod@1.15.2-1.2.0 DONE}
		SolarFluxReborn_1.15.2_15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		Trapcraft-1.15.2-2.7.0.jar Trapcraft {trapcraft@2.7.0 DONE}
		AutoRegLib-1.15.2.jar AutoRegLib {arl@1.5-36 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha DONE}
		elevatorid-1.15.2-1.5.5.jar Elevator Mod {elevatorid@1.15.2-1.5.5 DONE}
		mcw-roofs-1.0.1-mc1.15.2.jar Macaw's Roofs {mcwroofs@1.0.1 DONE}
		YAMDA-Mod-1.15.2.jar YAMDA {yamda@5.0.1 DONE}
		Sulfur-and-Potassium-Mod-1.15.2.jar Sulfur And Potassium - make gunpowder {sulfurpotassiummod@2.3.0 DONE}
		Pretty-Beaches-Mod-1.15.2.jar Pretty Beaches {prettybeaches@4.0.0 DONE}
		Cyclic-Mod-1.15.2.jar Cyclic {cyclic@1.15.2-0.1.7 DONE}
		Better-Advancements-Mod-1.15.2.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
		Automatic-Door-Mod-1.15.2.jar Automatic Doors {autodoors@1.3 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Double-Doors-Mod-1.15.2.jar Double Doors {doubledoors@1.2 DONE}
		Advanced-Finders-Mod-1.15.2.jar Advanced Finders {adfinders@4.0.0.0 DONE}
		Cucumber-1.15.2-3.0.0.jar Cucumber Library {cucumber@3.0.0 DONE}
		JANOEO-Mod-1.15.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.1.2 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		reap-1.12.0.jar Reap Mod {reap@1.12.0 DONE}
		Vulcanite-Ore-Mod-1.15.2.jar Vulcanite {vulcanite@2.0.3-mc1.15.2 DONE}
		Waystones_1.15.2_6.0.0.jar Waystones {waystones@6.0.0 DONE}
		More-Ores-In-ONE-Mod-1.15.2.jar More Ores in ONE {moreoresinone@1.1 DONE}
		Ores-Above-Diamonds-Mod-1.15.2.jar Ores Above Diamonds {oresabovediamonds@3.0 DONE}
		Natures-Compass-Mod-1.15.2.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		good-nights-sleep-1.15.2-1.0.1.jar Good Night's Sleep {goodnightsleep@1.0.1 DONE}
		Simple-Storage-Network-Mod-1.15.2.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 DONE}
		Serene-Seasons-Mod-1.15.2.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.49 DONE}
		McJtyLib-1.15.2.jar McJtyLib {mcjtylib@1.15-4.0.0-alpha DONE}
		RFTools-Base-Mod-1.15.2.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha DONE}
		RFTools-Storage-Mod-1.15.2.jar RFToolsStorage {rftoolsstorage@1.15-1.0.1-alpha DONE}
		Travellers-Boots-Mod-1.15.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		Mining-Gadgets-Mod-1.15.2.jar Mining Gadgets {mininggadgets@1.3.0 DONE}
		SteveKunGs-Lib-1.15.2.jar SteveKunG's Lib {stevekungs_lib@3.0.0 DONE}
		RFTools-Power-Mod-1.15.2.jar RFToolsPower {rftoolspower@1.15-2.0.0-alpha DONE}
		GemsPlusPlus-Mod-1.15.2.jar GemsPlusPlus {gemsplusplus@V1.4.1 DONE}
		swampexpansion-1.15.2-1.5.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 DONE}
		ruins-1.15.1.3.jar Ruins {ruins@1.15.1.3 DONE}
		Explorercraft-Mod-1.15.2.jar Explorercraft {explorercraft@1.15.2-4.0.0 DONE}
		EXP-Bottling-Mod-1.15.2.jar EXP Bottling {exp_bottling@1.15.2-1 DONE}
		Sound-Device-Options-Mod-1.15.2.jar Sound Device Options {sounddeviceoptions@1.3.0 DONE}
		Miners-Advantage-Mod-1.15.2.jar MinersAdvantage {minersadvantage@1.15.2-1.6.1.7 DONE}
		forge-1.15.2-31.1.18-client.jar Minecraft {minecraft@1.15.2 DONE}
		RFTools-Utility-Mod-1.15.2.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		Mouse-Tweaks-Mod-1.15.2.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		Titanium-Library-1.15.2.jar Titanium {titanium@2.3.6 DONE}
		InstaHouses-Mod-1.15.2.jar Slashkings InstaHouses {instahouses@1.1 DONE}
		Silent-Lib-1.15.2.jar Silent Lib {silentlib@4.6.0+48 DONE}
		ShayBoxs-Durability101-Mod-1.15.2.jar Durability101 {durability101@0.0.3 DONE}
		RFTools-Builder-Mod-1.15.2.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		dimdungeons_1.03_forge_1.15.2.jar Dimensional Dungeons {dimdungeons@1.14.4-1.03 DONE}
		Jerrys-Mod-1.15.2.jar Jerry's Mod {jerrysmod@1.15.2.1 DONE}
		flux-4.12.3.jar Flux {flux@4.12.3 DONE}
		fl-3.1.5.jar Flux Library {fl@3.1.5 DONE}
		Xaeros_Minimap_20.5.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.1 DONE}
		[1.15.2]+SecurityCraft+v1.8.17.jar SecurityCraft {securitycraft@v1.8.17 DONE}
		Storage-Drawers-Mod-1.15.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		Performant-Mod-1.15.2.jar Performant {performant@1.7 DONE}
		engineersdecor-1.15.2-1.0.19-b1.jar Engineer's Decor {engineersdecor@1.0.19-b1 DONE}
		Refined-Relocation-2-Mod-1.15.2.jar Refined Relocation {refinedrelocation@7.0.0 DONE}
		Oh-The-Biomes-Youll-Go-Mod-1.15.2.jar Oh The Biomes You'll Go {byg@0.0.1 DONE}
		Refined-Storage-Addons-1.15.2.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Solar-Generation-Mod-1.15.2.jar Solar Generation {solargeneration@1.2.0 DONE}
		Thutmoses-Elevators-Mod-1.15.2.jar Thut Elevators {thuttech@8.0.0.a DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		ThutCore-1.15.2.jar Thut Core {thutcore@7.0.0.b DONE, thutcrafts@7.0.0.b DONE}
		Vanilla+-Tools-Mod-1.15.2.jar Vanilla+ Tools {supertools@version DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: 1.15.2-forge-31.1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/PixaGraph+16x16+-+1.15+-+1.16.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700 Eight-Core Processor 

The game crashed whilst tesselating block model
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: rfto

**Comment by McJty** [comment]
This is extremely weird. I do notice you have a somewhat older version of forge though. Maybe try updating that first?

**Comment by McJty** [comment]
Also you are not using the latest version of my mods either. Where did you get those mods from? They have very weird filenames

**Comment by christomite** [comment]
i either got them from curseforge.com or 9minecraft.net ill try to update forge oh i also moved my minecraft folder and had to change some things around to get it to work on my ssd that might explain the weird filenames

**Comment by McJty** [comment]
Never ever get mods from 9minecraft.net! That's an illegal mod repost site and mods on that site are not to be trusted at all!. Also make sure to update my mods. You're not using the latest

**Comment by christomite** [comment]
what would be the best place can i get a link so i make sure im using the right one please.
im kind of new to modded minecraft so i appreciate the info

**Comment by christomite** [comment]
i got it thank you so much i downloaded all the newest mods from you and it totally worked thanks allot i appreciate it very much!!!!!!!
